// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KartverketProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251109034033_FixGuid")]
    partial class FixGuid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("KartverketProject.Models.Obstacle", b =>
                {
                    b.Property<int>("ObstacleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ObstacleId"));

                    b.Property<string>("ObstacleDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<double>("ObstacleHeight")
                        .HasColumnType("double");

                    b.Property<string>("ObstacleJSON")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObstacleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ObstacleStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ObstacleSubmittedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ObstacleId");

                    b.ToTable("Obstacle");

                    b.HasData(
                        new
                        {
                            ObstacleId = 1,
                            ObstacleDescription = "This is a test obstacle.",
                            ObstacleHeight = 10.5,
                            ObstacleJSON = "{\"type\":\"FeatureCollection\",\"features\":[]}",
                            ObstacleName = "Test Obstacle",
                            ObstacleStatus = "Pending",
                            ObstacleSubmittedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("KartverketProject.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<int>("ObstacleId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("ReportId");

                    b.HasIndex("ObstacleId");

                    b.HasIndex("UserId");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("KartverketProject.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "799673c2-7bcc-4d11-ad1f-b8688dd76b8d",
                            AccessFailedCount = 0,
                            Active = true,
                            ConcurrencyStamp = "9e1a9bd6-793f-4fc3-ab70-052051729ca8",
                            Email = "admin@gorm.no",
                            EmailConfirmed = false,
                            FirstName = "John",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GORM.NO",
                            NormalizedUserName = "ADMIN@GORM.NO",
                            PasswordHash = "AQAAAAIAAYagAAAAENoAqm4Grb7ufYUw4ZAWL+4M2w6fKHcKozu01+ehDeA7S2cdt0lwX5g5Y7u6oPrqfA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9e5e0b5b-36f9-4116-832c-772a22837378",
                            TwoFactorEnabled = false,
                            UserName = "admin@gorm.no"
                        },
                        new
                        {
                            Id = "8ea604ed-9171-41f0-b120-355587373608",
                            AccessFailedCount = 0,
                            Active = true,
                            ConcurrencyStamp = "ee3b8df7-35b8-4466-8c5a-dc71624de307",
                            Email = "reviewer@gorm.no",
                            EmailConfirmed = false,
                            FirstName = "Jane",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "REVIEWER@GORM.NO",
                            NormalizedUserName = "REVIEWER@GORM.NO",
                            PasswordHash = "AQAAAAIAAYagAAAAEGEYPjTHD0MR5OXBSp2bo7JKqPjyTdPc7RfLwbDCw/hyWUAZBZgNEDgR4N/vjLE/Vw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c84b73e3-3450-40fc-acf1-e5a57a174317",
                            TwoFactorEnabled = false,
                            UserName = "reviewer@gorm.no"
                        },
                        new
                        {
                            Id = "0bc5e074-efff-4996-a268-fd2a69f8bba5",
                            AccessFailedCount = 0,
                            Active = true,
                            ConcurrencyStamp = "4761dda5-c378-4834-99fc-85ca4ee55d3e",
                            Email = "user@gorm.no",
                            EmailConfirmed = false,
                            FirstName = "Bob",
                            LastName = "Smith",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@GORM.NO",
                            NormalizedUserName = "USER@GORM.NO",
                            PasswordHash = "AQAAAAIAAYagAAAAELLV+mpQQTif/n3teGoqPO5ZTVJbmfvGb5gU9xsFiN7PywPU/VjYyShUzZKgqslQcQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "aced0b06-0a25-46ce-a771-961b5135261c",
                            TwoFactorEnabled = false,
                            UserName = "user@gorm.no"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "5cf4e46d-19d6-4f70-ac4a-b64be1df8473",
                            ConcurrencyStamp = "5cf4e46d-19d6-4f70-ac4a-b64be1df8473",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2575cf3e-3c0b-49c3-9320-86cfed7e8cde",
                            ConcurrencyStamp = "2575cf3e-3c0b-49c3-9320-86cfed7e8cde",
                            Name = "reviewer",
                            NormalizedName = "REVIEWER"
                        },
                        new
                        {
                            Id = "89578426-a858-4b61-bad1-1d732e38e6d1",
                            ConcurrencyStamp = "89578426-a858-4b61-bad1-1d732e38e6d1",
                            Name = "user",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "799673c2-7bcc-4d11-ad1f-b8688dd76b8d",
                            RoleId = "5cf4e46d-19d6-4f70-ac4a-b64be1df8473"
                        },
                        new
                        {
                            UserId = "8ea604ed-9171-41f0-b120-355587373608",
                            RoleId = "2575cf3e-3c0b-49c3-9320-86cfed7e8cde"
                        },
                        new
                        {
                            UserId = "0bc5e074-efff-4996-a268-fd2a69f8bba5",
                            RoleId = "89578426-a858-4b61-bad1-1d732e38e6d1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KartverketProject.Models.Report", b =>
                {
                    b.HasOne("KartverketProject.Models.Obstacle", "Obstacle")
                        .WithMany("ReportEntries")
                        .HasForeignKey("ObstacleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KartverketProject.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Obstacle");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("KartverketProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("KartverketProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KartverketProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("KartverketProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KartverketProject.Models.Obstacle", b =>
                {
                    b.Navigation("ReportEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
